services:
  jenkins:
    build:
      context: jenkins/
      target: production

    ports:
      - 8080:${JENKINS_PORT_WEB:-8080}
      - 50000:${JENKINS_PORT_AGENT:-50000}
    environment:
      - JENKINS_ADMIN_PASSWORD=${JENKINS_ADMIN_PASSWORD}
      - DOCKER_HUB_USERNAME=${DOCKER_HUB_USERNAME}
      - DOCKER_HUB_PASSWORD=${DOCKER_HUB_PASSWORD}
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock

  agent:
    build:
      context: app/
      target: agent
    environment:
      - JENKINS_URL=${JENKINS_URL}
      - JENKINS_AGENT_NAME=docker-agent
      - JENKINS_ADMIN_PASSWORD=${JENKINS_ADMIN_PASSWORD}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - agent_workspace:/home/jenkins/agent

  app-test:
    build:
       context: app/
       target: test
    profiles: ["test"]

  app:
    image: app:latest
    build:
      context: app/
      target: production
    ports:
      - ${flask_app_port:-5000}:5000

volumes:
  jenkins_home:
  agent_workspace:
