jenkins:
  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: "admin"
          password: "${JENKINS_ADMIN_PASSWORD}"
  authorizationStrategy:
    loggedInUsersCanDoAnything:
      allowAnonymousRead: false
  nodes:
    - permanent:
        name: "docker-agent"
        remoteFS: "/home/jenkins"
        labelString: "linux build-node"
        numExecutors: 2
        mode: NORMAL
        launcher:
          inbound: {}

credentials:
  system:
    domainCredentials:
      - credentials:
          - usernamePassword:
              scope: GLOBAL
              id: "docker-hub-credentials"
              description: "Docker Hub credentials"
              username: "${DOCKER_HUB_USERNAME}"
              password: "${DOCKER_HUB_PASSWORD}"

security:
  globalJobDslSecurityConfiguration:
    useScriptSecurity: false
  csrf:
    defaultCrumbIssuer:
      excludeClientIPFromCrumb: true

jobs:
  - script: >
      pipelineJob('flask-pipeline') {
        triggers {
          githubPush()
        }
        definition {
          cpsScm {
            scm {
              git {
                remote {
                  url('https://github.com/avivdan/ubiquitous-barnacle.git')
                  credentials('')
                }
                branch('*/main')
              }
            }
            scriptPath('Jenkinsfile')
          }
        }
      }